# Generated by Django 5.0.2 on 2024-05-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interview',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
