# Generated by Django 5.0.2 on 2024-05-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewmaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': (('can_add_users', 'Can add users'), ('can_schedule_interview', 'Can schedule interviews'))},
        ),
    ]
